services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"
    extra_hosts:
      - "mfukui.42.fr:127.0.0.1"

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    expose:
      - "9000"
    extra_hosts:
      - "mfukui.42.fr:127.0.0.1"

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    extra_hosts:
      - "mfukui.42.fr:127.0.0.1"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/mfukui/docker/volumes/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/mfukui/docker/volumes/wordpress

networks:
  inception:
    driver: bridge
