services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file :
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_SITE_TITLE: ${WP_SITE_TITLE}
    restart: always

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/mfukui/data/mariadb
      o: bind

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /Users/mfukui/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
